### ISSUE TITLE
Default arguments of train_lightgbm() don't match those of lightgbm::lgb.train()

### ISSUE THREAD

**Issue by lorenzwalthert** [curso-r/treesnip#25]
```r
lgb.train(
  params = list(),
  data,
  nrounds = 10L,
  valids = list(),
  obj = NULL,
  eval = NULL,
  verbose = 1L,
  record = TRUE,
  eval_freq = 1L,
  init_model = NULL,
  colnames = NULL,
  categorical_feature = NULL,
  early_stopping_rounds = NULL,
  callbacks = list(),
  reset_data = FALSE,
  ...
)

# and 
train_lightgbm(
  x,
  y,
  max_depth = 6,
  num_iterations = 100,
  learning_rate = 0.1,
  feature_fraction = 1,
  min_data_in_leaf = 1,
  min_gain_to_split = 0,
  bagging_fraction = 1,
  ...
)

```

In `?parsnip::boost_tree()` it says about arguments:
 
> If left to their defaults here (NULL), the values are taken from the underlying model functions.

Then for me it would be intuitive that in `train_lightgbm()` would inherit from `lightgbm::lgb.train()`, either explicitly c/p them as defaults or implicitly (by setting them to `NULL`). That way, we could ensure that using {parsnip} or a native API (e.g. {lightgbm}) would give the same results with the defaults. What is the rationale behind not doing this?

**Comment by Athospd** [comment]
@lorenzwalthert thanks!

There was no specific reason for those defaults. Just legacy code for dev purpouses.

But there is just one thing to point out. [Parsnip doesn't allow tree_depth < 1](https://github.com/tidymodels/parsnip/blob/d251c73b2b6281e98f64282db9c55fcd8f229394/R/boost_tree.R#L246) so I decided to set tree_depth = 17 as default because `num_leaves` is constrained in `1 < num_leaves <= 131072` by lightgbm itself.
